// <auto-generated />
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;

#pragma warning disable 219, 612, 618
#nullable enable

namespace WebScheduler.DataMigrations.CompiledModels
{
    [DbContext(typeof(OrleansDbContext))]
    public partial class OrleansDbContextModel : RuntimeModel
    {
        static OrleansDbContextModel()
        {
            var model = new OrleansDbContextModel();
            model.Initialize();
            model.Customize();
            _instance = model;
        }

        private static OrleansDbContextModel _instance;
        public static IModel Instance => _instance;

        partial void Initialize();

        partial void Customize();
    }
}
